name: event_pulse
description: "A events related demo project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

    flutter_local_notifications: ^18.0.1
    firebase_core: ^3.8.0
    firebase_messaging: ^15.1.5
    cupertino_icons: ^1.0.2
    flutter_spinkit: ^5.2.1
    lottie: ^3.1.3
    google_maps_flutter: ^2.10.0
    flutter_form_builder: ^9.5.0
    dio: ^5.7.0
    provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Regular.ttf
         - asset: fonts/Poppins-Bold.ttf
         - asset: fonts/Poppins-Black.ttf
         - asset: fonts/Poppins-Medium.ttf
         - asset: fonts/Poppins-Light.ttf